### ISSUE TITLE
[PROJECT IDEA] Single page web app in front of Mark’s exchange rates scraper

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-ideas#13]
## Rationale

@markbrough has a scraper here:
https://morph.io/markbrough/exchangerates-scraper

…for anyone after historical exchange rate information. Morph.io provides an API, but it might be nice to demo this by adding a web frontend, similar to https://org-id-finder.codeforiati.org

**Comment by andylolz** [comment]
I’ve had a go at this here:
https://exchangerates.codeforiati.org

**Comment by matmaxgeds** [comment]
Ace - I anticipate sending all sorts of the colleagues I train to use it, rather than google as other historical xrate sites are hard to navigate or not free.
