### ISSUE TITLE
[BLOG IDEA] Write something about new replicated codelists site

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-ideas#14]
## What’s the blog about?

It would be cool to introduce the replicated codelists site, either on discuss or on https://codeforiati.org

## What’s the goal of the blog?

 * Momentum!
 * Make people aware of this service
 * Get some feature requests

**Comment by markbrough** [comment]
Done!!

**Comment by andylolz** [comment]
It’s here: https://codeforiati.org/blog/2020/02/10/making-third-party-codelists-more-accessible/
