### ISSUE TITLE
[PROJECT IDEA] Fork IATI-Website-Tests and get it running again

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-ideas#20]
## Rationale

Services should provide a status dashboard, so users know if they’re working as expected. Like this one:
https://www.githubstatus.com

We have https://uptime.codeforiati.org which tells us whether sites are up, but this is very high level – it doesn’t tell us if the sites are working as expected.

[IATI-Website-Tests](https://github.com/IATI/IATI-Website-Tests) is a monitoring service for IATI services. It includes a number of checks for different services, to check they’re working as expected.

However, a) it doesn’t appear to be running anymore, and b) we’ve identified some issues with it (e.g. the datastore checks are incorrect).

## Proposal

It would be cool to:
 * Fork [IATI-Website-Tests](https://github.com/IATI/IATI-Website-Tests)
 * Fix it (e.g. the issue with datastore checks mentioned above)
 * get it running daily again (on github actions, or circleCI, or travisCI)

**Comment by andylolz** [comment]
It’s now running daily here: https://travis-ci.com/codeforIATI/IATI-Website-Tests

**Comment by matmaxgeds** [comment]
@andylolz - do I need a travis login to see this, otherwise it is suggesting that the repository is not at the link above?

**Comment by andylolz** [comment]
Hmm…! That link *should* work without a travis login… I renamed the repo, which might be the cause of the problem? What do you see when you [click the travis link](https://travis-ci.com/github/codeforIATI/iati-service-monitor)?

**Comment by matmaxgeds** [comment]
Hey - the specific link works fine, just the top level one gives me this (see screenshot) so I don't think it is a dealbreaker

![Screenshot from 2020-07-14 11-42-18](https://user-images.githubusercontent.com/432153/87410943-44b38180-c5c7-11ea-83b5-ad84b3d03e82.png)

**Comment by andylolz** [comment]
Aha, yes – that’s because I renamed the repo.

I’ve *hopefully* eradicated all instances of that URL! Let me know if you spot it anywhere else. 

This URL should continue to work, even if you’re not signed in to travis:
https://travis-ci.com/codeforIATI/iati-service-monitor

**Comment by andylolz** [comment]
I’ve added a very tiny dashboard: https://monitor.codeforiati.org
