### ISSUE TITLE
[PROJECT IDEA] IATI publishers list

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/iati-ideas#27]
## Rationale

Getting a "codelist" of current IATI publishers would help organisations trying to match up their data

## Proposal

Pull the list from https://www.iatiregistry.org/publisher and format into a list on https://codelists.codeforiati.org/
Synch this list etc

Note : this would be different from https://org-id-finder.codeforiati.org/ - as that service includes many thousands of references from the org files (Global Giving account for over 9,000 orgs)

**Comment by andylolz** [comment]
I think this happens already…

Here’s the codelist:
https://codelists.codeforiati.org/ReportingOrganisation/

Updater is here:
https://github.com/codeforIATI/codelist-updater/blob/8dbb9d4a/importers/reporting_organisation.py

Here’s a recent update:
https://github.com/codeforIATI/Unofficial-Codelists/pull/112

**Comment by matmaxgeds** [comment]
Is there a use case for putting the orgs from org-id-finder on the codelists site e.g. https://codelists.codeforiati.org/Organisation_IDs/ or similar.......I guess just another way to suck in the org_id_finder list for those already using the codelists and api they present?

**Comment by stevieflow** [comment]
Thanks @andylolz - doh!

@matmaxgeds I wouldnt yet pull the references from org-id-finder into a list atm.  As mentioned, this is pulling data from the org files, which are not fully "verified"
