### ISSUE TITLE
[PROJECT IDEA] Provide easy access to codes for public bodies

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-ideas#32]
## Rationale

There have been many discussions over the years of how to identify public bodies, but they haven't gotten us to an easy way of categorising government public bodies. [In this discussion](https://discuss.iatistandard.org/t/discussion-post-identifying-government-entities/729/21), I proposed using the codes used in government national budgets / charts of accounts. I haven't seen or read anything since then that dissuades me from the idea that this is the best, most sustainable, and most reliable way of coding public bodies.

This is the "missing piece" of being able to identify organisations in IATI data. For private companies, NGOs, donors and multilateral institutions, there is generally a methodology that already exists:

* for private companies or NGOs, use the national registration agency's identifier for this organisation, or VAT / tax number
* for donors and multilateral institutions, use DAC codes

Reliable, stable, authoritative codes for public bodies already exist: the government chart of accounts. These codes are almost always visible in the national budget, which is always a public document.

## Proposal

* Allow one CSV file per country to be stored in a repository in a standardised format. The filename should be according to the country code.
* Make this information searchable (possibly integrated with [codeforiati/org-id-finder](https://github.com/codeforiati/org-id-finder))
* The files would be provided as a convenience, but the authoritative source remains the government chart of accounts or national budget.
* This would make organisation identifiers of the form {ISO 3166-2 country code}-GOV-{organisation code}
* The code for the Liberian Ministry of Health would be `LR-GOV-310`.

For Liberia, the file would be `LR.csv`, and some sample data might be: 

code | name
--- | ---
310 | Ministry of Health
311 | John F. Kennedy medical Center
312 | Phebe Hospital and School of Nursing
313 | Liberia Institute of Bio-Meical Research

--------

**Screenshot: [Liberia FY20/21 national budget](https://mfdp.gov.lr/index.php/main-menu-reports/mm-bdp/mm-bd-nb/national-budget-fy-2020-2021/download) - extract from p3**
![image](https://user-images.githubusercontent.com/688113/113610710-02dad780-963d-11eb-8c54-7c588a8ec8f2.png)

**Comment by matmaxgeds** [comment]
- Similarly keen
- Suspect the WB Boost DB might be a good shortcut to get a large set of CoAs (and if not the CoAs themselves, the budget classifications that use them)
- I would tweak it to use LR-CoA_2001-310 though as CoAs in my experience are reissued annually with small changes

**Comment by markbrough** [comment]
So definitely agree with first two points. Also think `LR-CoA` is a better prefix.

On the third point, I was thinking about this before - [see point (2) in this post](https://discuss.iatistandard.org/t/discussion-post-identifying-government-entities/729/21), because indeed there can be changes from year to year. However, I think I am leaning against this because it adds additional costs and the benefits seem to me to be unclear / dealing with edge cases:
* it seems like there are generally no dramatic changes from year to year in CoAs, at least for the organisation codes for major administrative unit
* codes _can_ be re-used, but I think this is normally unlikely to happen in a problematic way (by problematic I mean  "health" becoming "education", rather than "health" becoming "health and social welfare"), also because of the effects it would have in terms of internal keys used in IFMIS
* having to check the year of the CoA is maybe some additional burden? and what if you have the CoA codes for 2021 but not for 2020... do you just not use them at all, or should we encourage people to use something that is going to be right 99% of the time?
* knowing that `LR-CoA_2021-310` is the same as `LR-CoA_2019-310` seems quite a bit more complicated than just assuming that `LR-CoA-310` is constant. I think this would lead to a large number of duplicate identifiers and would make it a bit more difficult to just select all data where the implementing organisation is `310`
* we would probably then have a strong argument for maintaining mapping tables mapping 2019-310 to 2021-310... which I don't really want to do!

I guess generally wary of making the perfect the enemy of the good, especially given what we know about existing IATI tools. Perhaps to make a good decision on this we would need to know if codes are frequently re-used in a problematic way?

**Comment by matmaxgeds** [comment]
Yep, understood - is a good compromise to just pick the CoA from one year e.g. CoA_2021 and not bother to add any others, that way:
- if there is a match on 310, probably no need to do anything as codes are rarely reused
- but if the data series/values really did change in a suspicious way.....then at least knowing the CoA match was from 2021 - e.g. if you were doing this in 2025, then you would know what to check to work out what was wrong
- Although codes rarely change e.g. splitting the Ministry of Health into a Ministry of Health, and a separate Agency for Drugs Procurement is probably slightly more common, you would still get a hit on 310 for Health, but should be suspicious that the values have dropped hugely as some have left for 327 - National Drugs Procurement Agency......so you could then see that this Agency did not exist in CoA 2021 and at least know what has happened so you could alert users that the codelist is invalid for 301 after e.g. 2024?

**Comment by markbrough** [comment]
Covered in #52 and implemented in:
https://gov-id-finder.codeforiati.org/
