### ISSUE TITLE
[PROJECT IDEA] Standard navigation between major projects

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-ideas#33]
## Rationale

At the moment, we have inconsistent or sometimes no links between major Code for IATI projects. It would be nice to make things more easily discoverable.

## Proposal

I think we might want to link to a few major projects:
* Codelists
* Dashboard
* Datastore
* ? possibly codeforiati.org ?

Not sure how this should be implemented! There are a few options:

1. Have an additional level of navigation above the main navigation, which is hidden when you scroll down (and becomes a hamburger on mobile)
2. Add a hamburger next to the Code for IATI logo revealing this additional navigation (but it might be unclear what it is doing)
3. Add the links only in the footer?

In addition, I think the status page would be good to add to the footer.

**Comment by andylolz** [comment]
This exists now: https://codeforiati.org/sidebar/
