### ISSUE TITLE
[PROJECT IDEA] Discord server

### ISSUE THREAD

**Issue by notshi** [codeforIATI/iati-ideas#36]
## Rationale

At the time of writing, the Discord server for IATI seems to have vanished from the server list. At least to me.
It was great to have a somewhat organic hub for IATI related discussions that was easy to hop on and off.

## Proposal

Maybe we should have an official codeforIATI discord server.

The previous Discord server was somewhat full of passive participants. It would be good to have more a committed and active community in this new one by inviting a small number of people first.

I am aware that there is an IRC channel but messages disappear and it doesn't have all the gubbins of discord; ie. channels, voice chat, screenshare etc.

**Comment by andylolz** [comment]
> At the time of writing, the Discord server for IATI seems to have vanished from the server list. At least to me.
> It was great to have a somewhat organic hub for IATI related discussions that was easy to hop on and off.

^^ Oh no! That is sad… Yes, it seems to have disappeared.

> I am aware that there is an IRC channel

There is, but I don’t think it’s used (in fact I think we should remove mention of it, see: codeforIATI/codeforIATI.github.io#49).

My preference would be a slack workspace, but I’m also fine with discord.

**Comment by notshi** [comment]
> My preference would be a slack workspace, but I’m also fine with discord.

Either platform is fine :}

It would be good to have this for the community, and attaching it to codeforiati should signal that it's active and by/for community members using IATI data.

**Comment by notshi** [comment]
I've made a Discord server! Do let me know if you want ownership - wasn't sure if it was okay to just make one.

https://discord.gg/UxvKPVMz

**Comment by notshi** [comment]
By the way, I compared Slack and Discord and went with the latter because of the pricing.
Eventually, Slack will just delete posts unless you give them money (there's a threshold) and that's no good - don't appreciate data being held hostage.

**Comment by andylolz** [comment]
Slack doesn’t delete the posts – they keep them, but you can’t see them. So yeah, held hostage is right. But gotta have a business model I guess!

**Comment by andylolz** [comment]
Closing this, thanks for making it happen @notshi!

**Comment by siemvaessen** [comment]
Could a new (permanent) link be shared? The old link has expires. Thanks.

**Comment by andylolz** [comment]
I’ve just fixed the link on the [get-involved page](https://codeforiati.org/get-involved/).
