### ISSUE TITLE
[PROJECT IDEA] Host RSS feeds for iatistandard.org and iaticonnect.org

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-ideas#45]
## Rationale

https://iatistandard.org and https://iaticonnect.org do not currently provide RSS feeds. I currently use http://fetchrss.com to fill the gap, which works really well. However:
 * The free version only updates every 24 hours. I’d like to check for updates more frequently
 * It only sees "public" content on iaticonnect. I’d like to also see "community" content
 * The URLs are long and complicated, and they are not exposed anywhere

## Proposal

 * Create github actions that fetch news items (every 4 hours?) and push them to RSS feeds that are hosted on github pages.
 * Create a single page website at https://rss-feeds.codeforiati.org, that links to these RSS feeds.

**Comment by matmaxgeds** [comment]
This is a cool thing :)

Is it possible (beneficial) to add https://twitter.com/hashtag/IATI to the list?

**Comment by andylolz** [comment]
First pass at this:
https://rss-feeds.codeforiati.org
