### ISSUE TITLE
[PROJECT IDEA] Extend IATI Tables to cover Org files

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-ideas#46]
## Rationale
[IATI tables](https://iati-tables.codeforiati.org/) are great when you need to do some analysis that is not common enough to have a specific tool. Org files have very few tools that provide the info they include, the only options are using [iati-decipher](https://decipher.codeforiati.org/#) (publisher by publisher) or the registry/data dump

## Proposal
Add org files to IATI-tables

**Comment by andylolz** [comment]
Pinging @kindly about this one, in case they’ve not seen it.

**Comment by andylolz** [comment]
In fact… Might be worth adding the same issue over here:
https://github.com/codeforIATI/iati-tables/issues

**Comment by andylolz** [comment]
But FWIW I think this would be great

**Comment by matmaxgeds** [comment]
Cool, closing here and adding to the iati-tables repo
