### ISSUE TITLE
[PROJECT IDEA] Ensure cron jobs don’t switch off after 60 days of inactivity

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-ideas#47]
## Rationale

Code for IATI has a number of repos with github actions that run on a schedule. Often, these actions are doing work that involves updating a non-default branch, but don’t necessarily make any changes to the default branch.

[Github says](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows):
> In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

Updates to non-default branches does not count as "repository activity", so our scheduled actions are frequently being disabled. There’s no notification when an action is automatically disabled – it just stops running, and needs to be manually restarted.

## Proposal

There are a few different ways to tackle this:

 1. We could change the default branch on these repos, so that the updated branch is default. This will involve some shuffling about, since the README and workflow will need to stay on the default branch. We’ll lose version control on these files for instances where we deliberately scrub the history. Also, there’s no guarantee that this will fix the problem, since in some cases updates are less frequent than every 60 days
 2. We could have some separate service that uses the github API to check if a workflow has stopped, and give it a kick if so (I think @markbrough proposed this). I’ve no idea how difficult this is (EDIT: [here’s the relevant API endpoint](https://docs.github.com/en/rest/reference/actions#enable-a-workflow)), but it is much cleaner than the previous solution, and would work in all cases. It would still work on a schedule, so it would still need to be kept alive somehow.
 3. The scheduled action could make some other modification to the repo that ensures it is still considered active, e.g. post a comment on an issue. This feels very hacky, but it might actually be the easiest thing.

https://github.com/codeforIATI/status/issues/2 is somewhat related.

**Comment by markbrough** [comment]
Amazing work, thanks @andylolz !
