### ISSUE TITLE
[PROJECT IDEA] Update AndyLolz's IATI Traceability network visualisation and analysis

### ISSUE THREAD

**Issue by alexjtilley** [codeforIATI/iati-ideas#48]
## Rationale

AndyLolz produced this data network visualisation in 2019 which shows the transaction-based upstream and downstream linkages between activities in the IATI data: https://bl.ocks.org/andylolz/34dbc9e1d3ae04c5a331af1f978849f2 

This shows how often the transaction link function is being used by IATI publishers, who is using it and whether links are reciprocated. 

It would be helpful to see how this has changed since 2019, whether networking of data has increased or decreased and to what extent. An update of the visualisation would be great to see, as well as the quantitative analysis of number of links per organisation: 

<html>
<body>

Publisher ID | Downstream Links | Upstream Links | Grand Total
-- | -- | -- | --
Dfid | 16 | 1598 | 1614
minbuza_nl | 6 | 621 | 627
scuk | 1 | 518 | 519
manniondaniels | 150 | 45 | 195
be-dgd |   | 137 | 137
tripleline_crownagents | 102 | 3 | 105
irc_uk | 52 | 53 | 105
cordaid | 38 | 61 | 99
solidaridad-europe | 7 | 89 | 96
onl |   | 76 | 76

</body>
</html>

## Proposal

Run the same visualisation and analysis with the current IATI dataset.

**Comment by andylolz** [comment]
I’ll mark this as done in here… But if there are any issues or improvements you can think of, please raise them here:
https://github.com/codeforIATI/traceability-graph/issues
